# https://github.com/actions/deploy-pages#usage
name: deploy_to_ukraina_com_ua_main
on:
  workflow_dispatch:
  repository_dispatch:
    types: 
      - deploy_to_ukraina_com_ua_main
  push:
    branches:
      - master
jobs:
  build_main:
    runs-on: ubuntu-latest

    steps:
       
       # Step 5: Выполнение дополнительных команд на сервере
      - name: Run Commands on Remote Server Clean folder 
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            rm -rf /home/cyclone/fireon.com.ua/www/*
     # Step 1: Установка Node.js версии 18
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Указываем версию Node.js

      # Step 2: Checkout репозитория
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 3: Установка зависимостей и сборка
      - name: Install Dependencies and Build
        run: |
          npm install --legacy-per-deps
          npm run build  # Сборка проекта
   
          
                
      # Step 4: Deploy files with rsync
      - name: Deploy with Rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: .
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: ${{ secrets.REMOTE_PATH }}  

       # Step 5: Выполнение дополнительных команд на сервере
      - name: Run Commands on Remote Server Checking up
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            cd /home/cyclone/fireon.com.ua/www
            ls -la  # Просматриваем файлы, чтобы убедиться в загрузке
            echo "Deployment complete!"
          
  
     
