# https://github.com/actions/deploy-pages#usage
name: deploy_to_ukraina_com_ua
on:
  workflow_dispatch:
  repository_dispatch: 
    target: [deploy_to_ukraina_com_ua]
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: .
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: ${{ secrets.REMOTE_PATH }}  
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/cyclone/fireon.com.ua/www/
            rm -rf node_modules package-lock.json
            ls
            npm -v
            npm install
            npx nuxt build
     
