# https://github.com/actions/deploy-pages#usage
name: Deploy to Ukraina com ua
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: .
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: ${{ secrets.REMOTE_PATH }}  
      - name: deploy 
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: corepack enable
       
      # Pick your own package manager and build script
      - run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-per-deps
      - run: npx nuxt build
